version: "3"

services:
    app:
        build: ./app/
        container_name: uee-life
        restart: unless-stopped
        command:
            "npm run start"
    
    nginx:
        image: nginx
        container_name: uee-life-nginx
        ports:
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app