version: "3"

services:
    nuxt:
        build: ./app/
        container_name: uee-life-nuxt
        restart: unless-stopped
        ports:
            - "3000:3000"
        command:
            "npm run start"
    
    nginx:
        image: nginx
        container_name: ueelife-nginx
        ports:
            - "8090:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - nuxt