version: "3"

services:
    nuxt:
        build: ./app/
        container_name: uee-life
        restart: unless-stopped
        ports:
            - "3000:3000"
        command:
            "npm run start"
    
    nginx:
        image: nginx
        container_name: uee-life-nginx
        ports:
            - "8090:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - nuxt